Repository monsieurbiz/SyliusMediaManagerPlugin, pull requests merged in 2023-10, with the labels that each got.

#13 Remove duplicate prefix in route config
  recipes/1.0/config/routes/monsieurbiz_media_manager_plugin.yaml
Labels: Status: needs review, quick win

#14 Resolve several data_roots for svg images when liip_imagine filter is used
  src/Resources/config/services.yaml
  src/Resources/views/Admin/MediaManager/Modal/Content/Files/_previewFile.html.twig
  src/Twig/Extension/FilterExtensionDecorator.php
Labels: Status: needs review

#15 doc: Add banner in README
  README.md
  docs/images/banner.jpg
Labels: Status: needs review, documentation, quick win
